version: '3.8'
services:
  web:
    restart: always
    container_name: simpletodo
    build:
      context: .
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
